language: go
sudo: false
go:
  - 1.9.x
  - tip

env:
  - TESTS="-race -v -bench=. -coverprofile=coverage.txt -covermode=atomic"
  - TESTS="-race -v ./..."

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libunbound-dev
    - go get github.com/coredns/coredns
    - go get github.com/miekg/unbound


script:
  - go test $TESTS

after_success:
  - bash <(curl -s https://codecov.io/bash)
